name: Run Unit Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker-compose 
      run: docker-compose up --build -d
    - name: Run Cover Test
      run: go test -cover
    - name: Run Unit Tests
      run: go test -v
